name: Output the required information
on: workflow_dispatch
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github Metadata in JSON format
              run: echo "${{toJSON(github)}}"
